version: '3'
services:
  app:
    image: django-api:latest
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - django-project:/var/lib/postgresql/data

volumes:
  django-project: