# Generated by Django 2.2.1 on 2019-06-21 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_api', '0003_auto_20190621_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followees',
            field=models.ManyToManyField(blank=True, null=True, related_name='followees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
