# Generated by Django 2.2.1 on 2019-06-21 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_api', '0005_auto_20190621_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folow',
            new_name='Follow',
        ),
    ]
