# Generated by Django 2.2.1 on 2019-06-21 12:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_api', '0006_auto_20190621_1222'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('receiver', 'sender', 'status')},
        ),
    ]
