# Generated by Django 2.2.1 on 2019-06-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_auto_20190621_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Like'), (0, 'None')], default=1),
        ),
    ]
