# Generated by Django 2.2.1 on 2019-06-21 21:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_api', '0008_auto_20190621_2103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user_reacted', 'posts', 'status')},
        ),
    ]
