# Generated by Django 2.2.2 on 2019-07-06 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_api', '0010_auto_20190622_1340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('sender', 'receiver', 'status')},
        ),
    ]
