# Generated by Django 2.2.2 on 2019-07-06 22:45

import app_api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0011_auto_20190706_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.CharField(blank=True, default=app_api.helpers.code_generator, help_text='random code used for registration and for password reset', max_length=15, null=True, verbose_name='code'),
        ),
    ]
